name: CI
on: [push, pull_request]
env:
  OPENLOCO_BUILD_SERVER: GitHub
  OPENLOCO_VERSION: 21.02
jobs:
  mac:
    name: macOS legacy
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - shell: bash
        run: gem install xcode-install
      - shell: bash
        run: xcversion install 9.4.1
        env:
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
